Name: Pruthvik Kakadiya

UTA ID: 1001861545

Machine Learning (CSE-6363)

Programming Assignment 1

Matrix Factorization 


In [149]:
import numpy
import pandas as pd


In [150]:
def matrix_factorization(Matrix, P, Q, K, iterations=1000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(iterations):
        for i in range(len(Matrix)):
            for j in range(len(Matrix[i])):
                if Matrix[i][j] > 0:
                    element_ij = Matrix[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * element_ij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * element_ij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        error = 0
        for i in range(len(Matrix)):
            for j in range(len(Matrix[i])):
                if Matrix[i][j] > 0:
                    error = error + pow(Matrix[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        error = error + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if error < 0.001:
            break
    print("Matrix Factorization Completed")
    return P, Q.T



Try algorithm for a small test matrix

In [151]:
test_matrix = [[10,0,6,2],
               [6,3,0,0],
               [2,0,9,5]]
test = numpy.array(test_matrix)
N_test = len(test)
M_test = len(test[0])
K_test = 2
P_test = numpy.random.rand(N_test,K_test)
Q_test = numpy.random.rand(M_test,K_test)
new_P_test, new_Q_test = matrix_factorization(test, P_test, Q_test, K_test)
new_test_matrix = numpy.dot(new_P_test, new_Q_test.T)

Matrix Factorization Completed


Print the new test_matrix


In [152]:
new_test_matrix

array([[8.89564532, 3.92824798, 6.81045466, 2.48603253],
       [6.03460365, 2.78226786, 5.71446221, 2.39716167],
       [3.35255563, 2.05708911, 7.94047582, 4.42659599]])

Now take input1-1.csv file as input and run matrix factorization on that input file

In [153]:
input_matrix1 = pd.read_csv("input1-1.csv", header=None)
input_matrix1

0   1   2   3   4   5   6   7   8   9   ...  33  34  35  36  37  38  39  \
0    6   0   3   7   2   5   4   2   4   3  ...   1   6   4   8   6   0   0   
1    2   0   0   8   7   3   1   2   2   0  ...   8   7   3   5   2   4   6   
2    0   4   0   6   8   5   4   6   0   7  ...   3   0   2   5   9   3   1   
3    8   8   2   5   6   9   2   3   9   9  ...   2   9   3   5   4   6   2   
4    8   8   9   6   6   1   2   9   8   3  ...   4   3   0   1   4   9   5   
5    3   5   7   8   4   5   1   0   9   6  ...   3   5   0   5   7   2   4   
6    4   1   7   7   2   3   1   8   4   1  ...   0   4   3   0   3   2   6   
7    5   9   3   5   7   0   5   4   1   7  ...   1   7   3   3   7   0   6   
8    6   5   2   0   5   0   7   2   0   2  ...   0   4   4   0   9   5   9   
9    4   6   1   5   4   6   8   7   7   1  ...   3   4   0   7   6   6   3   
10   8   1   4   9   3   7   9   9   5   3  ...   3   7   2   1   5   3   5   
11   5   6   5   1   9   3   7   3   4   4  ...   8   5   8   0   8   2   8   
12   7   3   1   7   8   3   2   8   3   1  ...   7   7   7   5   8   3   1   
13   6   5   6   6   5   6   1   4   8   4  ...   9   4   6   6   0   0   7   
14   6   3   9   0   3   8   2   1   4   2  ...   5   1   7   3   0   0   2   
15   2   0   7   3   2   7   9   9   4   6  ...   4   2   7   6   7   4   2   

    40  41  42  
0    3   9   1  
1    6   8   1  
2    8   8   4  
3    7   3   4  
4    3   9   6  
5    7   9   2  
6    6   2   0  
7    6   5   7  
8    8   2   5  
9    5   7   9  
10   6   9   2  
11   6   9   2  
12   7   8   8  
13   5   4   0  
14   1   2   2  
15   6   1   8  

[16 rows x 43 columns]

In [154]:

matrix1 = numpy.array(input_matrix1)
N1 = len(matrix1)
M1= len(matrix1[0])
K1 = 2
P1 = numpy.random.rand(N1,K1)
Q1 = numpy.random.rand(M1,K1)
new_P1, new_Q1 = matrix_factorization(matrix1, P1, Q1, K1)
new_matrix1 = numpy.dot(new_P1, new_Q1.T)


Matrix Factorization Completed


Print the new matrix1

In [155]:
new_matrix1

array([[4.85405891, 4.37036192, 4.02535951, 5.39706228, 4.82595588,
        4.62334258, 3.89489065, 4.87794838, 4.49171681, 3.58771727,
        5.16700157, 5.70283934, 5.33682024, 4.94606346, 4.19411031,
        5.89950331, 3.38232391, 4.14572099, 4.58318582, 4.351604  ,
        4.51187775, 4.89698525, 4.95553901, 4.65105426, 3.39767428,
        5.24167227, 4.50440787, 5.18175053, 4.64171961, 3.97896663,
        4.63827118, 2.21922215, 5.02186323, 4.05686519, 4.75125138,
        4.29527035, 4.27398311, 5.55884942, 3.88668883, 4.08340924,
        5.30079795, 5.68785741, 4.10626844],
       [4.05029147, 3.34121509, 2.695944  , 5.48620267, 5.76484852,
        3.81980131, 4.28943791, 5.03625081, 2.86327042, 3.35006353,
        4.76367476, 6.35971637, 3.53155111, 5.482818  , 4.9332452 ,
        5.2933047 , 4.25699465, 4.17023981, 3.51906467, 6.49792962,
        4.17043382, 4.76813587, 5.16540326, 5.16394121, 4.6463873 ,
        6.40239986, 2.66248903, 5.40384923, 3.81776372, 3.64549097,
   

Now take input2.csv file as input and run matrix factorization on that input file

In [157]:
input_matrix2 = pd.read_csv("input2.csv", header=None)
input_matrix2

0   1   2   3   4   5   6   7   8   9   ...  33  34  35  36  37  38  39  \
0     8   0   0   4   0   1   8   6   9   8  ...   0   5   0   1   8   6   3   
1     6   2   0   3   9   0   7   0   2   1  ...   4   7   7   3   2   0   3   
2     5   4   2   8   3   7   7   0   9   4  ...   6   8   0   5   8   9   8   
3     9   8   7   8   4   5   5   9   5   9  ...   1   1   8   9   9   5   8   
4     6   0   2   2   7   3   3   3   5   7  ...   8   9   6   2   9   5   7   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
162   7   5   9   0   2   3   9   3   9   2  ...   5   4   9   5   7   6   0   
163   2   3   2   3   8   0   8   4   4   6  ...   6   6   5   2   4   5   7   
164   4   5   4   0   3   2   2   9   0   6  ...   2   6   0   4   2   5   6   
165   7   4   4   7   4   9   2   0   4   8  ...   1   1   7   8   0   6   1   
166   0   7   4   5   8   0   1   5   4   3  ...   2   5   4   6   5   3   4   

     40  41  42  
0     2   0   0  
1     0   2   8  
2     1   2   9  
3     4   3   4  
4     0   8   7  
..   ..  ..  ..  
162   0   2   1  
163   8   8   1  
164   1   1   4  
165   3   1   5  
166   4   7   5  

[167 rows x 43 columns]

In [158]:
matrix2 = numpy.array(input_matrix2)
N2 = len(matrix2)
M2= len(matrix2[0])
K2 = 2
P2 = numpy.random.rand(N2,K2)
Q2 = numpy.random.rand(M2,K2)
new_P2, new_Q2 = matrix_factorization(matrix2, P2, Q2, K2)
new_matrix2 = numpy.dot(new_P2, new_Q2.T)


Matrix Factorization Completed


Print the new matrix2

In [159]:
new_matrix2

array([[5.05467583, 5.17586741, 5.03475093, ..., 4.69891142, 5.03913678,
        4.75274452],
       [5.012207  , 4.05161368, 3.37539958, ..., 5.18510459, 4.18914073,
        6.60368182],
       [5.36350702, 5.01532823, 4.62901104, ..., 5.21790412, 4.99072426,
        5.87727609],
       ...,
       [4.70552792, 4.51554714, 4.23392632, ..., 4.52161678, 4.46477868,
        4.95422197],
       [4.75695951, 3.90699053, 3.29583163, ..., 4.89103917, 4.02192094,
        6.15942976],
       [5.61668226, 5.42009837, 5.09892333, ..., 5.38247844, 5.35187195,
        5.86072368]])